name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --global --unset-all http.https://github.com/.extraheader || true
        git config --global --unset-all core.sshCommand || true
    - name: Check Docker version
      run: docker --version
    - name: Pull latest Jekyll builder image
      run: docker pull jekyll/builder:latest
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future --verbose"
